### ISSUE TITLE
Add license to you repo.

### ISSUE THREAD

**Issue by arilow** [Zeni241/ESP32-NimbleBLE-For-Dummies#2]
I am not a lawyer. But based on [this article](https://levelup.gitconnected.com/code-on-github-is-not-free-197f93e4cd44), the code in this repo is not as open source as it might be intended to be. Citing it or creating derived work from it, requires explicit approval from the author.

Based on the README, you already collected and adapted code from other samples. So following the spirit I would like to ask you to add a license file with a common license script such as Apache 2, BSD 3-Clause, MIT, etc. You can find more information [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

I would appreciate a quick resolution as I need to present a final university project that includes the code in this repo and I would like to do it properly.

Thanks a lot!

**Comment by arilow** [comment]
Adding the same license that you have in [misc.c](https://github.com/Zeni241/ESP32-NimbleBLE-For-Dummies/blob/main/main/misc.c) to the other files would also do the trick :)

**Comment by Zeni241** [comment]
Hi arilow
Sorry for late reply. I have added MIT license file to the repo. You can use the code as you like.

**Comment by arilow** [comment]
Thanks a lot @Zeni241!!
